/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common.js";

export declare namespace AgrichainLedger {
  export type BatchInfoStruct = {
    publicIdHash: BytesLike;
    currentCustodian: AddressLike;
    currentOrgHash: BytesLike;
    custodyStage: BigNumberish;
    distributionStatus: BigNumberish;
    conditionStatus: BigNumberish;
    createdAt: BigNumberish;
  };

  export type BatchInfoStructOutput = [
    publicIdHash: string,
    currentCustodian: string,
    currentOrgHash: string,
    custodyStage: bigint,
    distributionStatus: bigint,
    conditionStatus: bigint,
    createdAt: bigint,
  ] & {
    publicIdHash: string;
    currentCustodian: string;
    currentOrgHash: string;
    custodyStage: bigint;
    distributionStatus: bigint;
    conditionStatus: bigint;
    createdAt: bigint;
  };

  export type PendingHandoffStruct = {
    sender: AddressLike;
    recipientWallet: AddressLike;
    recipientOrgHash: BytesLike;
    fromStage: BigNumberish;
    toStage: BigNumberish;
    initiatedAt: BigNumberish;
    expiresAt: BigNumberish;
    exists: boolean;
  };

  export type PendingHandoffStructOutput = [
    sender: string,
    recipientWallet: string,
    recipientOrgHash: string,
    fromStage: bigint,
    toStage: bigint,
    initiatedAt: bigint,
    expiresAt: bigint,
    exists: boolean,
  ] & {
    sender: string;
    recipientWallet: string;
    recipientOrgHash: string;
    fromStage: bigint;
    toStage: bigint;
    initiatedAt: bigint;
    expiresAt: bigint;
    exists: boolean;
  };
}

export interface AgrichainLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "DISTRIBUTOR_ROLE"
      | "EVALUATOR_ROLE"
      | "REGISTRAR_ROLE"
      | "RETAILER_ROLE"
      | "acceptDefaultAdminTransfer"
      | "anchorDigest"
      | "anchoredDigests"
      | "batches"
      | "beginDefaultAdminTransfer"
      | "cancelDefaultAdminTransfer"
      | "cancelHandoff"
      | "changeDefaultAdminDelay"
      | "confirmHandoff"
      | "defaultAdmin"
      | "defaultAdminDelay"
      | "defaultAdminDelayIncreaseWait"
      | "getBatch"
      | "getPendingHandoff"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initiateHandoff"
      | "owner"
      | "pause"
      | "paused"
      | "pendingDefaultAdmin"
      | "pendingDefaultAdminDelay"
      | "pendingHandoffs"
      | "recordCondition"
      | "recordValidAccess"
      | "registerBatch"
      | "renounceRole"
      | "revokeRole"
      | "riskFlagCount"
      | "rollbackDefaultAdminDelay"
      | "supportsInterface"
      | "unpause"
      | "validAccessCount",
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchRegistered"
      | "ConditionEvaluated"
      | "DefaultAdminDelayChangeCanceled"
      | "DefaultAdminDelayChangeScheduled"
      | "DefaultAdminTransferCanceled"
      | "DefaultAdminTransferScheduled"
      | "DigestAnchored"
      | "HandoffCancelled"
      | "HandoffConfirmed"
      | "HandoffInitiated"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "ValidAccessRecorded",
  ): EventFragment;

  encodeFunctionData(functionFragment: "DEFAULT_ADMIN_ROLE", values?: undefined): string;
  encodeFunctionData(functionFragment: "DISTRIBUTOR_ROLE", values?: undefined): string;
  encodeFunctionData(functionFragment: "EVALUATOR_ROLE", values?: undefined): string;
  encodeFunctionData(functionFragment: "REGISTRAR_ROLE", values?: undefined): string;
  encodeFunctionData(functionFragment: "RETAILER_ROLE", values?: undefined): string;
  encodeFunctionData(functionFragment: "acceptDefaultAdminTransfer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "anchorDigest",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "anchoredDigests", values: [BytesLike, BytesLike]): string;
  encodeFunctionData(functionFragment: "batches", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "beginDefaultAdminTransfer", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "cancelDefaultAdminTransfer", values?: undefined): string;
  encodeFunctionData(functionFragment: "cancelHandoff", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "changeDefaultAdminDelay", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "confirmHandoff", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "defaultAdmin", values?: undefined): string;
  encodeFunctionData(functionFragment: "defaultAdminDelay", values?: undefined): string;
  encodeFunctionData(functionFragment: "defaultAdminDelayIncreaseWait", values?: undefined): string;
  encodeFunctionData(functionFragment: "getBatch", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getPendingHandoff", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getRoleAdmin", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "grantRole", values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: "hasRole", values: [BytesLike, AddressLike]): string;
  encodeFunctionData(
    functionFragment: "initiateHandoff",
    values: [BytesLike, AddressLike, BytesLike, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pendingDefaultAdmin", values?: undefined): string;
  encodeFunctionData(functionFragment: "pendingDefaultAdminDelay", values?: undefined): string;
  encodeFunctionData(functionFragment: "pendingHandoffs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "recordCondition",
    values: [BytesLike, BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(functionFragment: "recordValidAccess", values: [BytesLike, BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerBatch",
    values: [BytesLike, BytesLike, AddressLike, BytesLike],
  ): string;
  encodeFunctionData(functionFragment: "renounceRole", values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: "revokeRole", values: [BytesLike, AddressLike]): string;
  encodeFunctionData(functionFragment: "riskFlagCount", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "rollbackDefaultAdminDelay", values?: undefined): string;
  encodeFunctionData(functionFragment: "supportsInterface", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "validAccessCount", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "DEFAULT_ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DISTRIBUTOR_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "EVALUATOR_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "REGISTRAR_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RETAILER_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "acceptDefaultAdminTransfer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anchorDigest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anchoredDigests", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "beginDefaultAdminTransfer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelDefaultAdminTransfer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelHandoff", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "changeDefaultAdminDelay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "confirmHandoff", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "defaultAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "defaultAdminDelay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "defaultAdminDelayIncreaseWait", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPendingHandoff", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRoleAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initiateHandoff", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingDefaultAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingDefaultAdminDelay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pendingHandoffs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordCondition", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordValidAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registerBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renounceRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "riskFlagCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rollbackDefaultAdminDelay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "supportsInterface", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "validAccessCount", data: BytesLike): Result;
}

export namespace BatchRegisteredEvent {
  export type InputTuple = [
    batchKey: BytesLike,
    publicIdHash: BytesLike,
    registrar: AddressLike,
    at: BigNumberish,
  ];
  export type OutputTuple = [batchKey: string, publicIdHash: string, registrar: string, at: bigint];
  export interface OutputObject {
    batchKey: string;
    publicIdHash: string;
    registrar: string;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionEvaluatedEvent {
  export type InputTuple = [
    batchKey: BytesLike,
    status: BigNumberish,
    reasonCode: BytesLike,
    at: BigNumberish,
  ];
  export type OutputTuple = [batchKey: string, status: bigint, reasonCode: string, at: bigint];
  export interface OutputObject {
    batchKey: string;
    status: bigint;
    reasonCode: string;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultAdminDelayChangeCanceledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultAdminDelayChangeScheduledEvent {
  export type InputTuple = [newDelay: BigNumberish, effectSchedule: BigNumberish];
  export type OutputTuple = [newDelay: bigint, effectSchedule: bigint];
  export interface OutputObject {
    newDelay: bigint;
    effectSchedule: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultAdminTransferCanceledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultAdminTransferScheduledEvent {
  export type InputTuple = [newAdmin: AddressLike, acceptSchedule: BigNumberish];
  export type OutputTuple = [newAdmin: string, acceptSchedule: bigint];
  export interface OutputObject {
    newAdmin: string;
    acceptSchedule: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DigestAnchoredEvent {
  export type InputTuple = [
    digest: BytesLike,
    periodKey: BytesLike,
    periodStart: BigNumberish,
    periodEnd: BigNumberish,
    at: BigNumberish,
  ];
  export type OutputTuple = [
    digest: string,
    periodKey: string,
    periodStart: bigint,
    periodEnd: bigint,
    at: bigint,
  ];
  export interface OutputObject {
    digest: string;
    periodKey: string;
    periodStart: bigint;
    periodEnd: bigint;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandoffCancelledEvent {
  export type InputTuple = [batchKey: BytesLike, sender: AddressLike, at: BigNumberish];
  export type OutputTuple = [batchKey: string, sender: string, at: bigint];
  export interface OutputObject {
    batchKey: string;
    sender: string;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandoffConfirmedEvent {
  export type InputTuple = [
    batchKey: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    fromStage: BigNumberish,
    toStage: BigNumberish,
    at: BigNumberish,
  ];
  export type OutputTuple = [
    batchKey: string,
    sender: string,
    recipient: string,
    fromStage: bigint,
    toStage: bigint,
    at: bigint,
  ];
  export interface OutputObject {
    batchKey: string;
    sender: string;
    recipient: string;
    fromStage: bigint;
    toStage: bigint;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandoffInitiatedEvent {
  export type InputTuple = [
    batchKey: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    recipientOrgHash: BytesLike,
    fromStage: BigNumberish,
    toStage: BigNumberish,
    expiresAt: BigNumberish,
    at: BigNumberish,
  ];
  export type OutputTuple = [
    batchKey: string,
    sender: string,
    recipient: string,
    recipientOrgHash: string,
    fromStage: bigint,
    toStage: bigint,
    expiresAt: bigint,
    at: bigint,
  ];
  export interface OutputObject {
    batchKey: string;
    sender: string;
    recipient: string;
    recipientOrgHash: string;
    fromStage: bigint;
    toStage: bigint;
    expiresAt: bigint;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
  export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidAccessRecordedEvent {
  export type InputTuple = [batchKey: BytesLike, publicReasonHash: BytesLike, at: BigNumberish];
  export type OutputTuple = [batchKey: string, publicReasonHash: string, at: bigint];
  export interface OutputObject {
    batchKey: string;
    publicReasonHash: string;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgrichainLedger extends BaseContract {
  connect(runner?: ContractRunner | null): AgrichainLedger;
  waitForDeployment(): Promise<this>;

  interface: AgrichainLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DISTRIBUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  EVALUATOR_ROLE: TypedContractMethod<[], [string], "view">;

  REGISTRAR_ROLE: TypedContractMethod<[], [string], "view">;

  RETAILER_ROLE: TypedContractMethod<[], [string], "view">;

  acceptDefaultAdminTransfer: TypedContractMethod<[], [void], "nonpayable">;

  anchorDigest: TypedContractMethod<
    [digest: BytesLike, periodKey: BytesLike, periodStart: BigNumberish, periodEnd: BigNumberish],
    [void],
    "nonpayable"
  >;

  anchoredDigests: TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;

  batches: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint] & {
        publicIdHash: string;
        currentCustodian: string;
        currentOrgHash: string;
        custodyStage: bigint;
        distributionStatus: bigint;
        conditionStatus: bigint;
        createdAt: bigint;
      },
    ],
    "view"
  >;

  beginDefaultAdminTransfer: TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;

  cancelDefaultAdminTransfer: TypedContractMethod<[], [void], "nonpayable">;

  cancelHandoff: TypedContractMethod<[batchKey: BytesLike], [void], "nonpayable">;

  changeDefaultAdminDelay: TypedContractMethod<[newDelay: BigNumberish], [void], "nonpayable">;

  confirmHandoff: TypedContractMethod<[batchKey: BytesLike], [void], "nonpayable">;

  defaultAdmin: TypedContractMethod<[], [string], "view">;

  defaultAdminDelay: TypedContractMethod<[], [bigint], "view">;

  defaultAdminDelayIncreaseWait: TypedContractMethod<[], [bigint], "view">;

  getBatch: TypedContractMethod<
    [batchKey: BytesLike],
    [AgrichainLedger.BatchInfoStructOutput],
    "view"
  >;

  getPendingHandoff: TypedContractMethod<
    [batchKey: BytesLike],
    [AgrichainLedger.PendingHandoffStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [void], "nonpayable">;

  hasRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [boolean], "view">;

  initiateHandoff: TypedContractMethod<
    [
      batchKey: BytesLike,
      recipientWallet: AddressLike,
      recipientOrgHash: BytesLike,
      expiresAt: BigNumberish,
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingDefaultAdmin: TypedContractMethod<
    [],
    [[string, bigint] & { newAdmin: string; schedule: bigint }],
    "view"
  >;

  pendingDefaultAdminDelay: TypedContractMethod<
    [],
    [[bigint, bigint] & { newDelay: bigint; schedule: bigint }],
    "view"
  >;

  pendingHandoffs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        sender: string;
        recipientWallet: string;
        recipientOrgHash: string;
        fromStage: bigint;
        toStage: bigint;
        initiatedAt: bigint;
        expiresAt: bigint;
        exists: boolean;
      },
    ],
    "view"
  >;

  recordCondition: TypedContractMethod<
    [batchKey: BytesLike, status: BigNumberish, reasonCode: BytesLike],
    [void],
    "nonpayable"
  >;

  recordValidAccess: TypedContractMethod<
    [batchKey: BytesLike, publicReasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerBatch: TypedContractMethod<
    [
      batchKey: BytesLike,
      publicIdHash: BytesLike,
      custodian: AddressLike,
      custodianOrgHash: BytesLike,
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [void], "nonpayable">;

  revokeRole: TypedContractMethod<[role: BytesLike, account: AddressLike], [void], "nonpayable">;

  riskFlagCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  rollbackDefaultAdminDelay: TypedContractMethod<[], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  validAccessCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "DISTRIBUTOR_ROLE"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "EVALUATOR_ROLE"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "REGISTRAR_ROLE"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "RETAILER_ROLE"): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptDefaultAdminTransfer",
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "anchorDigest",
  ): TypedContractMethod<
    [digest: BytesLike, periodKey: BytesLike, periodStart: BigNumberish, periodEnd: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchoredDigests",
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batches",
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint] & {
        publicIdHash: string;
        currentCustodian: string;
        currentOrgHash: string;
        custodyStage: bigint;
        distributionStatus: bigint;
        conditionStatus: bigint;
        createdAt: bigint;
      },
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "beginDefaultAdminTransfer",
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelDefaultAdminTransfer",
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelHandoff",
  ): TypedContractMethod<[batchKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeDefaultAdminDelay",
  ): TypedContractMethod<[newDelay: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmHandoff",
  ): TypedContractMethod<[batchKey: BytesLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "defaultAdmin"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "defaultAdminDelay"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultAdminDelayIncreaseWait",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBatch",
  ): TypedContractMethod<[batchKey: BytesLike], [AgrichainLedger.BatchInfoStructOutput], "view">;
  getFunction(
    nameOrSignature: "getPendingHandoff",
  ): TypedContractMethod<
    [batchKey: BytesLike],
    [AgrichainLedger.PendingHandoffStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin",
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole",
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasRole",
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "initiateHandoff",
  ): TypedContractMethod<
    [
      batchKey: BytesLike,
      recipientWallet: AddressLike,
      recipientOrgHash: BytesLike,
      expiresAt: BigNumberish,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(nameOrSignature: "owner"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "pause"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(nameOrSignature: "paused"): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingDefaultAdmin",
  ): TypedContractMethod<[], [[string, bigint] & { newAdmin: string; schedule: bigint }], "view">;
  getFunction(
    nameOrSignature: "pendingDefaultAdminDelay",
  ): TypedContractMethod<[], [[bigint, bigint] & { newDelay: bigint; schedule: bigint }], "view">;
  getFunction(
    nameOrSignature: "pendingHandoffs",
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        sender: string;
        recipientWallet: string;
        recipientOrgHash: string;
        fromStage: bigint;
        toStage: bigint;
        initiatedAt: bigint;
        expiresAt: bigint;
        exists: boolean;
      },
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordCondition",
  ): TypedContractMethod<
    [batchKey: BytesLike, status: BigNumberish, reasonCode: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordValidAccess",
  ): TypedContractMethod<[batchKey: BytesLike, publicReasonHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerBatch",
  ): TypedContractMethod<
    [
      batchKey: BytesLike,
      publicIdHash: BytesLike,
      custodian: AddressLike,
      custodianOrgHash: BytesLike,
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole",
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole",
  ): TypedContractMethod<[role: BytesLike, account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "riskFlagCount",
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rollbackDefaultAdminDelay",
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface",
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(nameOrSignature: "unpause"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validAccessCount",
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getEvent(
    key: "BatchRegistered",
  ): TypedContractEvent<
    BatchRegisteredEvent.InputTuple,
    BatchRegisteredEvent.OutputTuple,
    BatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ConditionEvaluated",
  ): TypedContractEvent<
    ConditionEvaluatedEvent.InputTuple,
    ConditionEvaluatedEvent.OutputTuple,
    ConditionEvaluatedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultAdminDelayChangeCanceled",
  ): TypedContractEvent<
    DefaultAdminDelayChangeCanceledEvent.InputTuple,
    DefaultAdminDelayChangeCanceledEvent.OutputTuple,
    DefaultAdminDelayChangeCanceledEvent.OutputObject
  >;
  getEvent(
    key: "DefaultAdminDelayChangeScheduled",
  ): TypedContractEvent<
    DefaultAdminDelayChangeScheduledEvent.InputTuple,
    DefaultAdminDelayChangeScheduledEvent.OutputTuple,
    DefaultAdminDelayChangeScheduledEvent.OutputObject
  >;
  getEvent(
    key: "DefaultAdminTransferCanceled",
  ): TypedContractEvent<
    DefaultAdminTransferCanceledEvent.InputTuple,
    DefaultAdminTransferCanceledEvent.OutputTuple,
    DefaultAdminTransferCanceledEvent.OutputObject
  >;
  getEvent(
    key: "DefaultAdminTransferScheduled",
  ): TypedContractEvent<
    DefaultAdminTransferScheduledEvent.InputTuple,
    DefaultAdminTransferScheduledEvent.OutputTuple,
    DefaultAdminTransferScheduledEvent.OutputObject
  >;
  getEvent(
    key: "DigestAnchored",
  ): TypedContractEvent<
    DigestAnchoredEvent.InputTuple,
    DigestAnchoredEvent.OutputTuple,
    DigestAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "HandoffCancelled",
  ): TypedContractEvent<
    HandoffCancelledEvent.InputTuple,
    HandoffCancelledEvent.OutputTuple,
    HandoffCancelledEvent.OutputObject
  >;
  getEvent(
    key: "HandoffConfirmed",
  ): TypedContractEvent<
    HandoffConfirmedEvent.InputTuple,
    HandoffConfirmedEvent.OutputTuple,
    HandoffConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "HandoffInitiated",
  ): TypedContractEvent<
    HandoffInitiatedEvent.InputTuple,
    HandoffInitiatedEvent.OutputTuple,
    HandoffInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused",
  ): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
  getEvent(
    key: "RoleAdminChanged",
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted",
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked",
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused",
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "ValidAccessRecorded",
  ): TypedContractEvent<
    ValidAccessRecordedEvent.InputTuple,
    ValidAccessRecordedEvent.OutputTuple,
    ValidAccessRecordedEvent.OutputObject
  >;

  filters: {
    "BatchRegistered(bytes32,bytes32,address,uint64)": TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;
    BatchRegistered: TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;

    "ConditionEvaluated(bytes32,uint8,bytes32,uint64)": TypedContractEvent<
      ConditionEvaluatedEvent.InputTuple,
      ConditionEvaluatedEvent.OutputTuple,
      ConditionEvaluatedEvent.OutputObject
    >;
    ConditionEvaluated: TypedContractEvent<
      ConditionEvaluatedEvent.InputTuple,
      ConditionEvaluatedEvent.OutputTuple,
      ConditionEvaluatedEvent.OutputObject
    >;

    "DefaultAdminDelayChangeCanceled()": TypedContractEvent<
      DefaultAdminDelayChangeCanceledEvent.InputTuple,
      DefaultAdminDelayChangeCanceledEvent.OutputTuple,
      DefaultAdminDelayChangeCanceledEvent.OutputObject
    >;
    DefaultAdminDelayChangeCanceled: TypedContractEvent<
      DefaultAdminDelayChangeCanceledEvent.InputTuple,
      DefaultAdminDelayChangeCanceledEvent.OutputTuple,
      DefaultAdminDelayChangeCanceledEvent.OutputObject
    >;

    "DefaultAdminDelayChangeScheduled(uint48,uint48)": TypedContractEvent<
      DefaultAdminDelayChangeScheduledEvent.InputTuple,
      DefaultAdminDelayChangeScheduledEvent.OutputTuple,
      DefaultAdminDelayChangeScheduledEvent.OutputObject
    >;
    DefaultAdminDelayChangeScheduled: TypedContractEvent<
      DefaultAdminDelayChangeScheduledEvent.InputTuple,
      DefaultAdminDelayChangeScheduledEvent.OutputTuple,
      DefaultAdminDelayChangeScheduledEvent.OutputObject
    >;

    "DefaultAdminTransferCanceled()": TypedContractEvent<
      DefaultAdminTransferCanceledEvent.InputTuple,
      DefaultAdminTransferCanceledEvent.OutputTuple,
      DefaultAdminTransferCanceledEvent.OutputObject
    >;
    DefaultAdminTransferCanceled: TypedContractEvent<
      DefaultAdminTransferCanceledEvent.InputTuple,
      DefaultAdminTransferCanceledEvent.OutputTuple,
      DefaultAdminTransferCanceledEvent.OutputObject
    >;

    "DefaultAdminTransferScheduled(address,uint48)": TypedContractEvent<
      DefaultAdminTransferScheduledEvent.InputTuple,
      DefaultAdminTransferScheduledEvent.OutputTuple,
      DefaultAdminTransferScheduledEvent.OutputObject
    >;
    DefaultAdminTransferScheduled: TypedContractEvent<
      DefaultAdminTransferScheduledEvent.InputTuple,
      DefaultAdminTransferScheduledEvent.OutputTuple,
      DefaultAdminTransferScheduledEvent.OutputObject
    >;

    "DigestAnchored(bytes32,bytes32,uint256,uint256,uint64)": TypedContractEvent<
      DigestAnchoredEvent.InputTuple,
      DigestAnchoredEvent.OutputTuple,
      DigestAnchoredEvent.OutputObject
    >;
    DigestAnchored: TypedContractEvent<
      DigestAnchoredEvent.InputTuple,
      DigestAnchoredEvent.OutputTuple,
      DigestAnchoredEvent.OutputObject
    >;

    "HandoffCancelled(bytes32,address,uint64)": TypedContractEvent<
      HandoffCancelledEvent.InputTuple,
      HandoffCancelledEvent.OutputTuple,
      HandoffCancelledEvent.OutputObject
    >;
    HandoffCancelled: TypedContractEvent<
      HandoffCancelledEvent.InputTuple,
      HandoffCancelledEvent.OutputTuple,
      HandoffCancelledEvent.OutputObject
    >;

    "HandoffConfirmed(bytes32,address,address,uint8,uint8,uint64)": TypedContractEvent<
      HandoffConfirmedEvent.InputTuple,
      HandoffConfirmedEvent.OutputTuple,
      HandoffConfirmedEvent.OutputObject
    >;
    HandoffConfirmed: TypedContractEvent<
      HandoffConfirmedEvent.InputTuple,
      HandoffConfirmedEvent.OutputTuple,
      HandoffConfirmedEvent.OutputObject
    >;

    "HandoffInitiated(bytes32,address,address,bytes32,uint8,uint8,uint64,uint64)": TypedContractEvent<
      HandoffInitiatedEvent.InputTuple,
      HandoffInitiatedEvent.OutputTuple,
      HandoffInitiatedEvent.OutputObject
    >;
    HandoffInitiated: TypedContractEvent<
      HandoffInitiatedEvent.InputTuple,
      HandoffInitiatedEvent.OutputTuple,
      HandoffInitiatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "ValidAccessRecorded(bytes32,bytes32,uint64)": TypedContractEvent<
      ValidAccessRecordedEvent.InputTuple,
      ValidAccessRecordedEvent.OutputTuple,
      ValidAccessRecordedEvent.OutputObject
    >;
    ValidAccessRecorded: TypedContractEvent<
      ValidAccessRecordedEvent.InputTuple,
      ValidAccessRecordedEvent.OutputTuple,
      ValidAccessRecordedEvent.OutputObject
    >;
  };
}
